name: Release
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - name: Release
        uses: justincy/github-action-npm-release@2.0.2
        id: release
      - uses: actions/setup-node@v2
        if: steps.release.outputs.released == 'true'
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
        if: steps.release.outputs.released == 'true'
      - run: npm run build
        if: steps.release.outputs.released == 'true'
      - run: npm publish --provenance --access public
        if: steps.release.outputs.released == 'true'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}